#!/usr/bin/env bash
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Variables from input parameters
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfer file
scp -i "${SSH_KEY}" -o StrictHostKeyChecking=no "${FILE_PATH}" "${USERNAME}@${SERVER_IP}:~/"

