#!/usr/bin/env bash
# Configures Nginx to use a custom 404 page.

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Nginx configuration for custom 404 page
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name _;

    error_page 404 /custom_404.html;

    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    location = /custom_404.html {
        internal;
    }
}
EOF

# Restart Nginx to apply changes (without using systemctl)
service nginx reload

