#!/usr/bin/env bash
# This script outputs the correct answers for the network questions into 1answers.txt

# Output the answers into 1answers.txt
"2" # Answer for the first question
"2" # Answer for the second question
