#!/usr/bin/env bash
# This script outputs the correct answers for the network questions into 1-types_of_network

# Output the answers into 1-types_of_network
echo "3" > 1-types_of_network # Answer for the first question
echo "2" >> 1-types_of_network # Answer for the second question
echo "1" >> 1-types_of_network # Answer for the third question
