#!/usr/bin/env bash
# This script writes the correct answers for questions

# Output the answers to a file
echo "3" > 0answers.txt # Answer for question 1
echo "2" >> 0answers.txt # Answer for question 2
echo "1" >> 0answers.txt # Answer for question 3
