#!/usr/bin/env bash
# This script contains answers to questions about types of networks.

# Answers to the questions
# 1) What type of network a computer in local is connected to?
#   c) LAN
echo "3"

# 2) What type of network could connect an office in one building to another office in a building a few streets away?
#   b) WAN
echo "2"

# 3) What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?
#   a) Internet
echo "1"
