#!/usr/bin/env bash
# This script contains answers to questions about MAC and IP addresses.

# Answers to the questions
# 1) What is a MAC address?
#   b) The unique identifier of a network interface
echo "2"

# 2) What is an IP address?
#   a) Is to devices connected to a network what postal address is to houses
echo "1"
