#!/usr/bin/env bash
# This script contains answers to questions about TCP and UDP.

# Answers to the questions
# 1) Which statement is correct for the TCP box:
#   It is a protocol that is transferring data in a slow way but surely
echo "1"

# 2) Which statement is correct for the UDP box:
#   It is a protocol that is transferring data in a fast way and might lose data along in the process
echo "2"

# 3) Which statement is correct for the TCP worker:
#   Have you received boxes x, y, z?
echo "1"
