#!/usr/bin/env bash
# Fixes nginx listening on port 80
sudo pkill nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo nginx -c /etc/nginx/nginx.conf
sudo rm /run/nginx.pid
