#!/usr/bin/env bash
# Configure Nginx to listen on port 80

apt-get update
apt-get install -y nginx || true
sed -i 's/listen .*/listen 80 default_server;/g' /etc/nginx/sites-available/default && service nginx restart
