#!/bin/bash
., .., .bash_history, .bash_logout, .bashrc, .cache/, .config/, .profile, 1.txt, 2.txt, 3.txt, A.txt, B.txt, C.txt, D.txt, E.txt, F.txt, G.txt, H.txt, I.txt, J.txt, K.txt, L.txt, M.txt, N.txt, O.txt, P.txt, Q.txt, R.txt, S.txt, T.txt, U.txt, V.txt, W.txt, X.txt, Y.txt, Z.txt, a.txt, b.txt, c.txt, d.txt, e.txt, f.txt, g.txt, h.txt, i.txt, j.txt, k.txt, l.txt, m.txt, n.txt, o.txt, p.txt, q.txt, r.txt, s.txt, t.txt, u.txt, v.txt, w.txt, x.txt, y.txt, z.txt, test/, welcome/

