#!/usr/bin/env bash
# Manages the manage_my_process script

case $1 in
  start)
    # Start manage_my_process and save its PID
    bash manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    # Stop manage_my_process
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    # Restart manage_my_process
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    bash manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
