#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of 4-to_infinity_and_beyond and kill it
pid=$(pgrep -f '4-to_infinity_and_beyond')
if [[ -n $pid ]]; then
    kill "$pid"
    echo "4-to_infinity_and_beyond process terminated."
else
    echo "4-to_infinity_and_beyond process not found."
fi
