#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall

# Use pkill with the -f option to match the full command line of the process
pkill -f '4-to_infinity_and_beyond'
