#!/usr/bin/env bash
# This script displays "Best School" 10 times using a for loop.

for _ in {1..10}; do
    echo "Best School" # Loop iteration: $i is not used but declared to satisfy shellcheck
done
