#!/usr/bin/env bash
# This script displays each user's story from /etc/passwd

while IFS=':' read -r username password _ gid userinfo homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
