#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and specific messages for 4, 9, and 17.

i=1
while [ $i -le 20 ]; do
    echo -n "$i "
    case $i in
        4)
            echo "and then bad luck from China"
            ;;
        9)
            echo "and then bad luck from Japan"
            ;;
        17)
            echo "and then bad luck from Italy"
            ;;
        *)
            echo ""
            ;;
    esac
    ((i++))
done
