#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Fetch all lines that contain inet (IPv4) but not inet6, then use awk to print the second field (the IP address)
ip -4 addr | grep 'inet' | grep -v 'inet6' | awk '{print $2}' | cut -d'/' -f1
