#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080.

sudo sed -i 's/user\s\+root;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s\+80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo service nginx restart

pgrep -a nginx
sudo ss -tuln | grep ':8080'

