#!/usr/bin/env bash
# Create an RSA key pair with specific options

# Name of the private key file
KEY_NAME="school"

# Passphrase for the key
PASSPHRASE="betty"

# Number of bits in the key
BITS=4096

# Generate the RSA key pair with the specified passphrase and bits
ssh-keygen -t rsa -b $BITS -C "$KEY_NAME" -f $KEY_NAME -N "$PASSPHRASE" -q

echo "Key generation complete. Keys stored as $KEY_NAME and $KEY_NAME.pub"

